---
apiVersion: v1
kind: Service
metadata:
  name: mcq-app-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mcq-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - techtoabroad.com
      secretName: techtoabroad-tls-prod
  ingressClassName: nginx
  rules:
    - host: techtoabroad.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcq-app-service
                port:
                  number: 8080
